english = {
    "welcome message": "Welcome to the Tic Tac Toe game!",
    "start message": " The Tic Tac Toe game is starting. ",
    "end message": " The Tic Tac Toe game is ending. ",
    "draw message": "It's a draw. Please try the game again.\n",
    "replay message": "Do you want to play the game again? (y/n) : ",
    "invalid yes or no message": "You've entered an invalid value. Please enter either y or n.\n",
    "invalid position message": "Invalid value. Please enter the number of the desired position.\n",
    "invalid position range message": "You've selected a position that's already taken or exceeded the value of 1 ~ 9.",
    "reselect position message": "Please select the position again.\n",
    "round count message": '"Round {}"\n',
    "players intro message": "The first player is {first_player} (O).\nThe second player is {second_player} (X).\n",
    "move query message": "{}, please select a position to place your move. : ",
    "winner message": "Congratulations!!! {}, you have won.\n",
    "scoreboard message": "win",
}

korean = {
    "welcome message": "Tic Tac Toe 게임에 오신 걸 환영합니다!",
    "start message": " Tic Tac Toe 게임을 시작합니다. ",
    "end message": " Tic Tac Toe 게임을 종료합니다. ",
    "draw message": "비겼습니다. 게임을 다시 시작해 보세요.\n",
    "replay message": "게임을 다시 하시겠습니까? (y/n) : ",
    "invalid yes or no message": "잘못된 값을 입력했습니다. y/n 중 하나를 입력해 주세요.\n",
    "invalid position message": "잘못된 값을 입력했습니다. 해당 칸의 번호를 입력해 주세요.\n",
    "invalid position range message": "이미 수가 놓인 위치를 선택했거나, 1 ~ 9 값을 넘어갔습니다.",
    "reselect position message": "위치를 다시 선택해 주세요.\n",
    "round count message": '"{} 라운드"\n',
    "players intro message": "첫 번째 플레이어는 {first_player} (O)입니다.\n두 번째 플레이어는 {second_player} (X)입니다.\n\n",
    "move query message": "{}님, 놓을 위치를 선택해 주세요. : ",
    "winner message": "축하합니다!!! {}님이 이겼습니다.\n",
    "scoreboard message": "승",
}
